apiVersion: v1
kind: Service
metadata:
  name: go-web-hello
  labels:
    name: go-web-hello
spec:
  type: NodePort
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 31080
      name: go-web-hello
  selector:
    app: go-web-hello
